name: pokedex
description: "pokemon pokedex"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  mobx: ^2.3.0+1
  flutter_mobx: ^2.2.0+2
  dio: ^5.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  flutter_lints: ^3.0.1
  mobx_codegen: ^2.6.0+1

flutter:
  uses-material-design: true